### ISSUE TITLE
sprite->setCenter/getCenter broken ?

### ISSUE THREAD

**Issue by Cpasjuste** [CurryGuy/Kairy#2]
Hi Nanni, i think that sprite/node->setCenter/getCenter is broken/not working, or i didn't understand how it work.

**Comment by CurryGuy** [comment]
The center of a sprite basically is the center of rotation expressed in a value between 0 and 1.
The default value is 0.5 in both x and y axis. I've tried it several times and I think it should work.
There are some common values in Vec2 that you can pass to setCenter. For instance:
sprite->setCenter(Vec2::TopLeft);
Maybe I should document these functions or give them better names

**Comment by Cpasjuste** [comment]
Oh sorry i understand, i thought it was for setting/getting node position by it's center :)  Does it also modify setPostion (this could be usefull maybe) ? If it's only used for rotation maybe "setPivot" would be more appropriate for example. 
Thanks for the reply :+1:
