### ISSUE TITLE
ScaleTo/ScaleBy action centered

### ISSUE THREAD

**Issue by Cpasjuste** [CurryGuy/Kairy#3]
Hi,

I think that the scale actions should be performed from the center of the node/sprite, or at least give a way to do that.

**Comment by CurryGuy** [comment]
For doing that, the scale actions should update the node position too.
Maybe I should implement that

**Comment by Cpasjuste** [comment]
Yes, i think in most situation we would probably need to scale a node by it's center, but having the choice would be better.
